[[activity_wasm]]
name = "activity_sleepy"
location = "${DEPLOYMENT_DIR}/target/wasm32-wasip2/release/activity_sleepy.wasm"
exec.lock_expiry.seconds = 10
directories  = { enabled = true, reuse_on_retry = false} # Each execution run starts with an empty preopened directory.

[[workflow_wasm]]
name = "workflow_tutorial"
location = "${DEPLOYMENT_DIR}/target/wasm32-unknown-unknown/workflow/workflow_tutorial.wasm"
backtrace.sources = {".../src/lib.rs" = "${DEPLOYMENT_DIR}/workflow-tutorial/src/lib.rs"}

[[webhook_endpoint_wasm]]
name = "webhook_tutorial"
location = "${DEPLOYMENT_DIR}/target/wasm32-wasip2/webhook/webhook_tutorial.wasm"
routes = ["/*"]
backtrace.sources = {".../src/lib.rs" = "${DEPLOYMENT_DIR}/webhook-tutorial/src/lib.rs"}
