package any:any;

world any {
    export tutorial:workflow/workflow;
    // Needed for `step`, calls the activity directly:
    import tutorial:activity/activity-sleepy;
    // Needed for `step-concurrent`, calls the activity using a join set:
    import tutorial:activity-obelisk-ext/activity-sleepy;
    import obelisk:types/execution@3.0.0;
    import obelisk:workflow/workflow-support@3.0.0;
}
